version: '3.3'
services:
  asir_bind9:
    container_name: asir_bind9
    image: internetsystemsconsortium/bind9:9.16
    ports:
      - 5300:53/udp
      - 5300:53/tcp
    networks:
      bind9_subnetasir:
        ipv4_address: 10.28.0.254
    volumes:
      - /home/asir2a/Documentos/SRI/dns/conf:/etc/bind
      - /home/asir2a/Documentos/SRI/dns/zonas:/var/lib/bind
  asir_cliente:
    container_name: asir_cliente
    image: alpine
    networks:
      - bind9_subnetasir
    stdin_open: true
    tty: true
    dns:
      -10.28.0.254
networks:
  bind9_subnetasir:
    external: true